### ISSUE TITLE
League data available?

### ISSUE THREAD

**Issue by bergi11** [amanthedorkknight/fifa18-all-player-statistics#1]
Is it possible to attach a league attribute to the data? Or do you have a mapping from clubs to the leagues?

**Comment by 4m4n5** [comment]
I could create a mapping table. Will post on this issue when complete.

**Comment by SHIVAPRASAD96** [comment]
When I run the program on IPython the attribute data is not getting collected. Would be happy if you can help me with it.

**Comment by amanthedorkknight** [comment]
``

**Comment by SHIVAPRASAD96** [comment]
I think the website is updated with respect to attributes part, because only the attributes aren't getting scraped. Is it because of the class names have changed?

**Comment by ghost** [comment]
Have a look at the data for FIFA 19: https://www.kaggle.com/karangadiya/fifa19
