### ISSUE TITLE
Minor improvement suggestions

### ISSUE THREAD

**Issue by huangl6** [amanthedorkknight/fifa18-all-player-statistics#2]
Hi, first of all, thanks for creating the crawler and collecting the info into an easily accessible file. While playing around with the 2019 csv file, I came across a couple of things that you might want to take into consideration.

1. convert the file to UTF-8 BOM encoding. When opening the file in Excel, a lot of the special characters are read incorrectly, leading into various kinds of gibberish. I fixed this on my end by converting the file into utf-8 BOM in notepad++.

2. Every 60 rows there is a duplicate entry. Following your offset method of iterating on each page, I think you'll notice that the last player from one page becomes the first player on the next. Perhaps ignoring the first player of every page after the first page would make cleaning up the data just a little easier.

3. Columns calculating each player's "FUT Card" stats. This allows us to more easily and quickly get an aggregated view on each player's abilities. Of course, the weightings on the calculations can be discussed and disputed but for quick exploratory purposes this might be useful to have.

**4. There are several players with positions listed as "RES" (i.e. Koscielny, Cech, Yarmolenko) or "SUB". Seems like sofifa decided to list the positions weirdly and if they are a reserve or sub on the team sheet they get listed as such (This one, maybe not so minor) The number of "RES" players is 3091 and the number of "SUB" players is 8037.

Would appreciate your thoughts on these suggestions! Also, are you going to be posting this on Kaggle like you did for the FIFA 18 dataset?

**Comment by 4m4n5** [comment]
Thanks for the reports. Will work on the mentioned issues and update the script soon. 

Yeah the data is up on Kaggle already - https://www.kaggle.com/karangadiya/fifa19

**Comment by huangl6** [comment]
Huh, didn't find that when searching for datasets. Thanks for the link!

**Comment by ghost** [comment]
1) Seems like converting to utf-8 wasn't enough for some columns to be in the proper format. Fixed the format to utf-8-sig, it should work now.
2) Removed the duplicated entries.
3) Good suggestion - the page structure is a bit weird for these stats so will have to dig deeper into it. will work on this soon...
4) I have fixed the positions for these players by replacing them with the most preferred position as it appears on the player page.

The new dataset has also been uploaded on Kaggle.

**Comment by huangl6** [comment]
For 3, it might be worth considering just calculating these values yourself if crawling proves to be a headache. There was some discussion on futwiz(?) trying to figure out the stat weights that go into the aggregated stats and they proved to be nearly, if not completely 100% accurate. I think the discussion into what determines each stat is also an interesting topic but that can be for another time
