### ISSUE TITLE
Error executing the code

### ISSUE THREAD

**Issue by alokpradeep11** [amanthedorkknight/fifa18-all-player-statistics#6]
Hello,

I found the project very interesting and i would like to work on analyzing the dataset which is returned by executing the code.
but, unfortunately when i executed the code in pycharm i got the below error :
line 24, in <module>
    age = td[2].find('div').text.strip()
AttributeError: 'NoneType' object has no attribute 'text'

Could you please let me know why the error is occuring in the above case.
Please let me know if there is an updated code.

**Comment by 4m4n5** [comment]
Thanks for your interest. The website that the script is scraping changes a little bit every year. The existing code works on the 2019 version and will require some tweaks to work on the current version. If you end up doing it, feel free to submit a PR. 
Thanks.

**Comment by enaihali** [comment]
Dear all, 

To run the code with success you only have to change line 24, try with 
age = td[2].find('div') 
instead of 
age = td[2].find('div').text.strip()
It worked for me. 

Hope this will be helpful ;)
